// Generated by Apple Swift version 2.2 (swiftlang-703.0.17.4 clang-703.0.28)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import QuartzCore;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class ComponentBody;
@class ComponentColumn;
@class ComponentArrow;
@class NSCoder;

SWIFT_CLASS("_TtC5Staff10Accidental")
@interface Accidental : CALayer

/// Position of the .
///
/// <blockquote><code>y
/// </code> value generally being on a staff line, or equidistance between two.<code>x
/// </code> values of a column of accidentals are aligned.</blockquote>
@property (nonatomic, readonly) CGPoint point;

/// Graphical height of a single Guidonian staff space
@property (nonatomic, readonly) CGFloat staffSpaceHeight;

/// Scale.
@property (nonatomic, readonly) CGFloat scale;
@property (nonatomic, readonly) CGFloat gS;
@property (nonatomic, readonly) CGFloat midWidth;
@property (nonatomic, readonly) CGFloat flankWidth;
@property (nonatomic, readonly) CGFloat thinLineWidth;
@property (nonatomic, readonly) CGFloat arrowHeight;
@property (nonatomic, copy) NSArray<CALayer *> * _Nonnull components;
@property (nonatomic, strong) ComponentBody * _Nullable body;
@property (nonatomic, strong) ComponentColumn * _Nullable column_left_up;
@property (nonatomic, strong) ComponentColumn * _Nullable column_left_down;
@property (nonatomic, strong) ComponentColumn * _Nullable column_center_up;
@property (nonatomic, strong) ComponentColumn * _Nullable column_center_down;
@property (nonatomic, strong) ComponentColumn * _Nullable column_right_up;
@property (nonatomic, strong) ComponentColumn * _Nullable column_right_down;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_left_up;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_left_down;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_center_up;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_center_down;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_right_up;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_right_down;
@property (nonatomic, readonly) CGColorRef _Nonnull color;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)createComponents;
- (void)commitComponents;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff19AccidentalComponent")
@interface AccidentalComponent : CAShapeLayer
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) CGFloat staffSpaceHeight;
@property (nonatomic) CGFloat scale;
@property (nonatomic, readonly) CGFloat gS;
@property (nonatomic) BOOL hasBeenBuilt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (CGRect)makeFrame;
- (CGPathRef _Nonnull)makePath;
@end


SWIFT_CLASS("_TtC5Staff9StaffClef")
@interface StaffClef : CALayer
@property (nonatomic, readonly) CGFloat extenderLength;
@property (nonatomic, readonly) CGFloat lineWidth;
@property (nonatomic, readonly) CGFloat middleCPosition;
@property (nonatomic, copy) NSArray<CALayer *> * _Nonnull components;
@property (nonatomic) CGFloat x;
@property (nonatomic, readonly) CGFloat staffTop;
@property (nonatomic, readonly) CGFloat staffSpaceHeight;
- (nonnull instancetype)initWithX:(CGFloat)x staffTop:(CGFloat)staffTop staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)createComponents;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff8AltoClef")
@interface AltoClef : StaffClef
@property (nonatomic, readonly) CGFloat ornamentAltitude;
@property (nonatomic, readonly) CGFloat middleCPosition;
- (nonnull instancetype)initWithX:(CGFloat)x staffTop:(CGFloat)staffTop staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff8BassClef")
@interface BassClef : StaffClef
@property (nonatomic, readonly) CGFloat ornamentAltitude;
@property (nonatomic, readonly) CGFloat middleCPosition;
- (nonnull instancetype)initWithX:(CGFloat)x staffTop:(CGFloat)staffTop staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)createComponents;
@end


SWIFT_CLASS("_TtC5Staff6Circle")
@interface Circle : CAShapeLayer
@property (nonatomic, readonly) CGPoint point;
@property (nonatomic, readonly) CGFloat radius;
- (nonnull instancetype)initWithPoint:(CGPoint)point radius:(CGFloat)radius lineWidth:(CGFloat)lineWidth color:(CGColorRef _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff14ComponentArrow")
@interface ComponentArrow : AccidentalComponent
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) CGPoint point;
@property (nonatomic, strong) ComponentColumn * _Nullable column;
@property (nonatomic, readonly) CGFloat contractionStepSize;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff13ComponentBody")
@interface ComponentBody : AccidentalComponent
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic) CGPoint point;
@property (nonatomic, readonly) CGFloat midWidth;
@property (nonatomic, readonly) CGFloat flankWidth;
@property (nonatomic) CGFloat thickLineSlope;
@property (nonatomic, readonly) CGFloat thickLineWidth;
@property (nonatomic, readonly) CGFloat thickLineLength;
@property (nonatomic, readonly) CGFloat thickLineΔY;
- (CGFloat)getYAtX:(CGFloat)x;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff17ComponentBodyFlat")
@interface ComponentBodyFlat : ComponentBody
@property (nonatomic, readonly) CGFloat bowlLineWidthTop;
@property (nonatomic, readonly) CGFloat bowlLineWidthBottom;
@property (nonatomic, readonly) CGFloat bowlLineWidthStress;
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale point:(CGPoint)point OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff20ComponentBodyNatural")
@interface ComponentBodyNatural : ComponentBody
@property (nonatomic, readonly) CGFloat thickLineLength;
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale point:(CGPoint)point OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff24ComponentBodyQuarterFlat")
@interface ComponentBodyQuarterFlat : ComponentBodyFlat
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale point:(CGPoint)point OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff25ComponentBodyQuarterSharp")
@interface ComponentBodyQuarterSharp : ComponentBody
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale point:(CGPoint)point OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff18ComponentBodySharp")
@interface ComponentBodySharp : ComponentBody
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale point:(CGPoint)point OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff15ComponentColumn")
@interface ComponentColumn : AccidentalComponent
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) CGFloat width;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y_internal;
@property (nonatomic) CGFloat y_external;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow;
- (nonnull instancetype)initWithStaffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale x:(CGFloat)x y_internal:(CGFloat)y_internal y_external:(CGFloat)y_external OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff7Diamond")
@interface Diamond : CAShapeLayer
@property (nonatomic, readonly) CGPoint point;
@property (nonatomic, readonly) CGFloat width;
- (nonnull instancetype)initWithPoint:(CGPoint)point width:(CGFloat)width lineWidth:(CGFloat)lineWidth color:(CGColorRef _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (CGRect)makeFrame;
- (CGPathRef _Nonnull)makePath;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff3Dot")
@interface Dot : CAShapeLayer
@property (nonatomic) CGPoint point;
@property (nonatomic) CGFloat radius;
- (nonnull instancetype)initWithPoint:(CGPoint)point radius:(CGFloat)radius color:(CGColorRef _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff4Flat")
@interface Flat : Accidental
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff8FlatDown")
@interface FlatDown : Flat
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff6FlatUp")
@interface FlatUp : Flat
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff18LedgerLinesSegment")
@interface LedgerLinesSegment : CAShapeLayer
@property (nonatomic, readonly) CGFloat staffSpaceHeight;
- (nonnull instancetype)initWithX:(CGFloat)x staffSpaceHeight:(CGFloat)staffSpaceHeight amountAbove:(NSUInteger)amountAbove amountBelow:(NSUInteger)amountBelow OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setPath;
- (void)setStyle;
@end


SWIFT_CLASS("_TtC5Staff4Line")
@interface Line : CAShapeLayer
@property (nonatomic, readonly) CGFloat height;
- (nonnull instancetype)initWithHeight:(CGFloat)height lineWidth:(CGFloat)lineWidth color:(CGColorRef _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)makeFrame;
- (CGPathRef _Nonnull)makePath;
@end


SWIFT_CLASS("_TtC5Staff7Natural")
@interface Natural : Accidental
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff11NaturalDown")
@interface NaturalDown : Natural
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff9NaturalUp")
@interface NaturalUp : Natural
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff8Notehead")
@interface Notehead : CAShapeLayer
@property (nonatomic) CGPoint point;
@property (nonatomic) CGFloat staffSpaceHeight;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGPathRef _Nonnull)makePath;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff11QuarterFlat")
@interface QuarterFlat : Accidental
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, strong) ComponentColumn * _Nullable column_up;
@property (nonatomic, strong) ComponentColumn * _Nullable column_down;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff15QuarterFlatDown")
@interface QuarterFlatDown : QuarterFlat
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_down;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff13QuarterFlatUp")
@interface QuarterFlatUp : QuarterFlat
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, strong) ComponentArrow * _Nullable arrow_up;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff12QuarterSharp")
@interface QuarterSharp : Accidental
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) CGFloat column_up_height;
@property (nonatomic, readonly) CGFloat column_down_height;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff16QuarterSharpDown")
@interface QuarterSharpDown : QuarterSharp
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) CGFloat column_down_height;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff14QuarterSharpUp")
@interface QuarterSharpUp : QuarterSharp
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) CGFloat column_up_height;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff5Sharp")
@interface Sharp : Accidental
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff9SharpDown")
@interface SharpDown : Sharp
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff7SharpUp")
@interface SharpUp : Sharp
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)createComponents;
- (nonnull instancetype)initWithPoint:(CGPoint)point staffSpaceHeight:(CGFloat)staffSpaceHeight scale:(CGFloat)scale OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC5Staff10StaffLayer")
@interface StaffLayer : CALayer
@property (nonatomic) CGFloat staffSpaceHeight;
@property (nonatomic, readonly) CGFloat lineWidth;
@property (nonatomic, readonly) CGFloat ledgerLineLength;
@property (nonatomic, readonly) CGFloat ledgerLineWidth;

/// Identifier.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSArray<StaffClef *> * _Nonnull clefs;
@property (nonatomic, copy) NSArray<CALayer *> * _Nonnull components;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nonnull)identifier staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (void)addNotehead:(Notehead * _Nonnull)notehead;

/// Start graph lines at the given x position.
- (void)startLinesAt:(CGFloat)x;

/// Stop graph lines at the given x position.
- (void)stopLinesAt:(CGFloat)x;
- (void)addLedgerLinesAt:(CGFloat)x amountAbove:(NSUInteger)amountAbove amountBelow:(NSUInteger)amountBelow;

/// Build the linesLayer.
- (void)buildLines;
- (void)build;

/// Build the eventsLayer
- (void)buildEvents;

/// Build the clefsLayer.
- (void)buildClefs;
- (CGRect)makeFrame;
@end


SWIFT_CLASS("_TtC5Staff17StaffLinesSegment")
@interface StaffLinesSegment : CAShapeLayer
@property (nonatomic, readonly) CGFloat staffSpaceHeight;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setPath;
- (void)setStyle;
@end


SWIFT_CLASS("_TtC5Staff9TenorClef")
@interface TenorClef : StaffClef
@property (nonatomic, readonly) CGFloat ornamentAltitude;
@property (nonatomic, readonly) CGFloat middleCPosition;
- (nonnull instancetype)initWithX:(CGFloat)x staffTop:(CGFloat)staffTop staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Staff10TrebleClef")
@interface TrebleClef : StaffClef
@property (nonatomic, readonly) CGFloat middleCPosition;
@property (nonatomic, readonly) CGFloat ornamentAltitude;
- (nonnull instancetype)initWithX:(CGFloat)x staffTop:(CGFloat)staffTop staffSpaceHeight:(CGFloat)staffSpaceHeight OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)createComponents;
@end

#pragma clang diagnostic pop
